library(sf)
dataDir = "C:/Users/angel.gimenez/Documents/DATA/"
# df = data.frame()
df = dfDataModel
# remove patterns in names that cannot be used in k.LAB as attributes in shapefiles
names(df) = sub("_","",names(df))
names(df) = sub("b0","zero",names(df))
names(df) = sub("b10","ten",names(df))
names(df) = sub("b30","xxx",names(df))
names(df) = sub("01","one",names(df))
names(df) = sub("02","two",names(df))
names(df) = sub("03","three",names(df))
names(df) = sub("04","four",names(df))
names(df) = sub("05","five",names(df))
names(df) = sub("06","six",names(df))
names(df) = sub("07","seven",names(df))
names(df) = sub("08","eight",names(df))
names(df) = sub("09","nine",names(df))
names(df) = sub("10","ten",names(df))
names(df) = sub("11","elvn",names(df))
names(df) = sub("12","twlv",names(df))
names(df) = sub("13","thtn",names(df))
names(df) = sub("14","frtn",names(df))
names(df) = sub("15","fftn",names(df))
names(df) = sub("16","sxtn",names(df))
names(df) = sub("17","svtn",names(df))
names(df) = sub("18","egtn",names(df))
names(df) = sub("19","nntn",names(df))
names(df) = sub("bio","",names(df))
names(df) = sub("sampling-year","year",names(df))

p.sf <- st_as_sf(df, coords = c("lon", "lat"), crs = 4326) 
st_write(p.sf, paste0(dataDir, "dataModelAndrenaFlavipes.shp"))
p.sf = st_read(paste0(dataDir,"OBServ/SDMs/Andrena_flavipes/dataModelAndrenaFlavipes.shp"))
